### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by gp-slick-coder** [Septh/ts-run#2]
Code:

``` typescript
import { Column, Model, PrimaryKey, Table } from "sequelize-typescript"

@Table
export class Setting extends Model<Setting> {
	@PrimaryKey
	@Column
	declare key: string

	@Column
	declare value: string
}
```

Error:

    P:\Repos\styrit-music\styrit-music-service>npx ts-run src\services\search-service.test.ts
    file:///P:/Repos/styrit-music/styrit-music-service/src/entities/setting.ts:19
    @Table
    ^
    
    SyntaxError: Invalid or unexpected token
        at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:152:18)
        at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:299:14)
    
    Node.js v18.20.2

br. g.

**Comment by Septh** [comment]
Yes, this is one the limitations of [Sucrase](https://github.com/alangpierce/sucrase), the parser used by `ts-run`. Quoting Sucrase's README.md:

> Decorators, private fields, throw expressions, generator arrow functions, and do expressions are all unsupported in browsers and Node (as of this writing), and Sucrase doesn't make an attempt to transpile them.

I should probably make this shine more in the docs.

**Comment by Septh** [comment]
> I should probably make this shine more in the docs.

And I just did.

Thanks for the report, anyway.

**Comment by gp-slick-coder** [comment]
OK, I see. Thanks for the info. I'm now at Vitest/esbuild and have the same issue.
